name: $(BuildDefinitionName)_$(date:yyMM).$(date:dd)$(rev:rrr)

trigger: none

resources:
  repositories:
  - repository: ComplianceRepo
    type: github
    endpoint: ComplianceGHRepo
    name: PowerShell/compliance

variables:
  - name: PackageName
    value: 'Microsoft.PowerShell.Archive'
  - name: PackageVersion
    value: ''
  - name: BuildOutDir
    value: ''

stages:
- stage: Build
  displayName: Build module
  pool:
      vmImage: windows-2019
  jobs:
  - job: BuildPkg
    displayName: Build module
    steps:

    - task: UseDotNet@2
      displayName: 'Get .NET 7.0 SDK'
      inputs:
        packageType: sdk
        version: 7.x
        includePreviewVersions: true

    - pwsh: |
        & "$(Build.SourcesDirectory)\Build.ps1"
      displayName: Build Microsoft.PowerShell.Archive module

    - task: CopyFiles@2
      displayName: 'Copy build'
      inputs:
        sourceFolder: '$(BuildOutDir)'
        contents: '**'
        targetFolder: '$(Build.ArtifactStagingDirectory)/Microsoft.PowerShell.Archive'

    - publish: '$(Build.ArtifactStagingDirectory)/Microsoft.PowerShell.Archive'
      displayName: 'Publish module build'
      artifact: ModuleBuild

- stage: Test
  dependsOn: Build
  displayName: Run tests
  jobs:
    - template: TestsTemplate.yml
      parameters:
        vmImageName: windows-2019
        jobName: run_test_windows
        jobDisplayName: Run Windows tests

    - template: TestsTemplate.yml
      parameters:
        vmImageName: ubuntu-latest
        jobName: run_test_linux
        jobDisplayName: Run Linux tests
    
    - template: TestsTemplate.yml
      parameters:
        vmImageName: macos-latest
        jobName: run_test_macos
        jobDisplayName: Run macOS tests
