parameters:
  - name: vmImageName
    type: string
    default: 'windows-2019'

  - name: jobName
    type: string
    default: 'run_test_windows'

  - name: jobDisplayName
    type: string
    default: 'Run test'

jobs:
  - job: myJob
    steps:
      - script: echo ${{ parameters.vmImageName }}